export const TOGGLE_IS_FETSHING = 'TOGGLE_IS_FETSHING';
export const ADD_POSTS = 'ADD_POSTS';
export const ADD_POST = 'ADD_POST';
export const ADD_COMMENT_VALUE = 'ADD_COMMENT_VALUE';
export const ADD_COMMENT_TO_POST = 'ADD_COMMENT_TO_POST';

